### ISSUE TITLE
✨ Feature Suggestion | Analytics

### ISSUE THREAD

**Issue by Domant3lis** [privacytools/privacytools.io#2205] opened 2021-01-30 11:47 UTC
## Description
Include a list of privacy respecting alternatives to Google Analytics for web developers to replace with. Could be put under "Provider" section.

I have gathered a possible list of products to put there:
[Plausible Analytics](https://plausible.io/)
[Goat Counter](https://www.goatcounter.com/)
[Simple Analytics](https://simpleanalytics.com/)
[Keep It Simple Stupid Stats](https://git.jlel.se/jlelse/kis3)

**Comment by Mikaela** [comment] 2021-01-30 14:11
Potentially duplicate of https://github.com/privacytools/privacytools.io/issues/1186

**Comment by freddy-m** [comment] 2021-01-30 17:45
I don't think that this is within the scope of the site. I'm closing this, but if anyone from @privacytools/editorial wants to reopen it thats fine.

**Closed by freddy-m** 2021-01-30 17:45 UTC
Labels: ✨ enhancement
