### ISSUE TITLE
📝 Correction | Quad9 re-incorporated in Switzerland.

### ISSUE THREAD

**Issue by Sauron462** [privacytools/privacytools.io#2246] opened 2021-04-01 20:48 UTC
Quad9 has stated they are now based in Sweden, and PTIO does not reflect this change.

Just wanted to let you guys know!

Source: https://quad9.net/news/blog/quad9-public-domain-name-service-moves-to-switzerland-for-maximum-internet-privacy-protection/

**Comment by freddy-m** [comment] 2021-04-01 22:17
Feel free to open a PR!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment] 2021-04-05 22:07
Hi @Sauron462, this issue is a duplicate of issue #2212.

**Comment by freddy-m** [comment] 2021-04-06 19:39
Duplicate of #2212.

Dealt with in #2214.

**Closed by freddy-m** 2021-04-06 19:39 UTC
Labels: 📝 correction, 🗄️ DNS
