### ISSUE TITLE
✨ Feature Suggestion | Video Streaming

### ISSUE THREAD

**Issue by nitrohorse** [privacytools/privacytools.io#1252] opened 2019-08-31 16:53 UTC
## Description:

Currently we don't have a "video streaming" section and a handful attempts to gain traction:
- https://github.com/privacytoolsIO/privacytools.io/issues/693
- https://github.com/privacytoolsIO/privacytools.io/issues/1029
- https://github.com/privacytoolsIO/privacytools.io/pull/1150
- https://github.com/privacytoolsIO/privacytools.io/pull/671
- https://github.com/privacytoolsIO/privacytools.io/pull/694

These are the software suggestions pulled from the above issue and PRs:

### Web / Self-hosted:
- [Invidious](https://invidio.us/) ([GitHub](https://github.com/omarroth/invidious))
- [MediaGoblin](https://mediagoblin.org/) ([Git](https://savannah.gnu.org/projects/mediagoblin))

### Web / P2P:
- [DTube](https://about.d.tube/) ([GitHub](https://github.com/dtube/dtube))
- [Peertube](https://joinpeertube.org/) ([GitHub](https://github.com/Chocobozzz/PeerTube))
- KopyKate ([GitHub](https://github.com/misses-robot/KopyKate-Big)) (appears dead)

### Mobile:
- [Newpipe](https://newpipe.schabi.org/) ([GitHub](https://github.com/TeamNewPipe/NewPipe)) (Android only)

### Desktop:
- [FreeTube](https://freetubeapp.io) ([GitHub](https://github.com/FreeTubeApp/FreeTube))

### Content Marketplace:
- [LBRY](https://lbry.com/) ([GitHub](https://github.com/lbryio)) (Desktop + Mobile)

We're at the point where a video stream page is needed but we need to resolve what will be listed. Any suggestions or ideas? I've attempted to categorize the software I found above as best as I can to make this easier.

**Comment by Mikaela** [comment] 2019-09-01 20:35
> We're at the point where a video stream page is needed

Why?

Who is the target audience of the video streaming page? In the original discussions about team chat, it was decided that the target audience is team admins even if that isn't clear from the current site (how to make it clear?), but with this issue that question arises again, is the target audience anyone or self-hosters? I especially wonder about MediaGoblin.

How is it more private to use invidio.us than YouTube (if the target audience is anyone)? It's not, you just change Google to whoever runs the Invidious instance, how to make this clear?

Is P2P private? This was a concern in some of the discussions, but I would still list them due to decentralization, but what is the correct balance?

**Comment by nitrohorse** [comment] 2019-09-08 21:41
> > We're at the point where a video stream page is needed
> 
> Why?
> 
I could've worded that better; what I meant to say was that it appears from the number of PRs + discussions that come up in the subreddit that having a video streaming section could help. The next question follows yours which is on target -- who is the audience? Just from my perspective it seems like the majority are simply users looking for a YouTube alternative or at least a streaming service with a decent privacy policy. This section could also target self-hosters; we could have subsections, one for YouTube alternatives and another for self-hosting software?

> How is it more private to use invidio.us than YouTube (if the target audience is anyone)? It's not, you just change Google to whoever runs the Invidious instance, how to make this clear?
> 
I think the primary privacy benefit of Invidious is the ability to proxy all YouTube videos through the instance ref: https://github.com/omarroth/invidious/wiki/Preferences). There is also an absence of Google's tracking and cookies to build a profile about what you watch (although you need to trust your instance also isn't doing that).

> Is P2P private? This was a concern in some of the discussions, but I would still list them due to decentralization, but what is the correct balance?

I don't think so, I'd gather P2P software was included in the previous PRs for anti-censorship reasons?

**Comment by ADepic** [comment] 2019-10-21 20:48
Alternatives like invidious and newpipe are definitely more private than YouTube, since all the videos are asked for by the app, and cannot be linked to an account or browser. For IP protection, simply use a vpn. 

On top of that, newpipe for example asks very little information making tracking possibilities harder.

By saying you are transferring tracking power from google to invidious instance runner, well you can say that about just about literally any online service, such as duckduckgo.

As for target audience, EVERYONE uses youtube, and so there needs to be a private way to view it.

**Comment by Mikaela** [comment] 2020-01-05 13:14
From our forum: https://forum.privacytools.io/t/reconsider-peertube/2385?u=mikaela

I would correct the link into https://github.com/Chocobozzz/PeerTube/blob/v2.0.0/config/default.yaml#L131-L139 as that is more permanent and shouldn't change as they add/remove/move options around.

*end content written by Mikaela* 

* * * * *

**Discussion**: Reconsider Peertube

_________________

_________________

**In relation to privacy and WebTorrent**:

First and foremost, WebTorrent can be turned off by the PeerTube instance:

- https://github.com/Chocobozzz/PeerTube/blob/develop/config/default.yaml#L134

Plus, I can confirm PeerTube does appear to work within the Tor Browser. :slight_smile:

**Previous Discussions**:

- https://github.com/privacytoolsIO/privacytools.io/issues/1252

**Comment by lrq3000** [comment] 2020-02-03 02:17
I support this issue, with detailed reasons in #1679.

Just my 2c on the various proposed solutions, as I have skimmed pretty much the whole web to find alternatives to YouTube:

* Invidious is great, I have discovered it with this PR, and it's a great solution for the audience to avoid tracking but still use YouTube. But it's not a solution for creators.
* The two most stable and future-proof solutions for creators to upload videos are PeerTube and LBRY.tv. Both use P2P to solve the problem of serving content without server farms (PeerTube via WebRTC, LBRY via their own app and not on LBRY.tv so less scalable for now but hopefully will implement WebRTC in the future). For both, there are already some [big names](http://traction.lbry.com/public/question/8dfc23e2-71e7-44cb-9740-0aec18d1da73) who uploaded their videos there (in parallel to YouTube).
* For monetization of creators, the best solution at the moment is on LBRY, with direct tipping from the interface using their internal blockchain based money. A limited amount is given everyday to users, so this creates a flowing economy, where the audience tips (instead of voting as it's not a planned feature).
* DTube has a very good model, including for monetization through voting instead of voluntary tipping, and it's also using P2P to serve videos, but it's currently highly unreliable. So much that since v0.9 they are serving videos [directly from other hosters](https://steemit.com/dtube/@dtube/dtube-0-9-doubling-up-your-rewards) such as YouTube, along with trackers (instead of mirroring as does LBRY in their [YouTube bridge program](https://lbry.com/youtube)).
* LBRY however has some privacy and functional issues:
  1. [cannot be embedded in other websites](https://www.reddit.com/r/lbry/comments/comxwm/how_do_i_embed_a_lbry_video_on_my_website/) (yet)
  2. log IPs and can link username to any actions on the blockchain (but [they are very transparent about that](https://lbry.com/faq/privacy-and-data)). Optionally can be tracked by Google Analytics if an option is enabled.
* Technically: LBRY is using a custom blockchain synchronized on Bitcoin Core + own DHT Kademlia implementation, whereas Dtube uses custom avalon blockchain (they moved on from steem) + DHT Kademlia.

My own conclusions:

* From an audience perspective, if only concerned by tracking but not by censorship, Insidious (and satellite apps) is the perfect solution to watch YouTube more privately (or even anonymously through the Tor node.
* From a hobbyist creator perspective with no remuneration expected, PeerTube is the most privacy aware platform for sharing videos, and also for the audience to avoid tracking.
* From a more professional creator perspective with remuneration expected, LBRY is currently the most stable platform. Privacy is not the best, but it's way better than YouTube or other centralized platforms.
* Dtube is a promising competitor, with a nice UX (similar to YouTube and other video streaming platforms, so the audience is not lost), but they have a big problem of latency and video availability, so unusuable for now IMO.

**Comment by DontUseGithub** [comment] 2020-02-13 11:08
> Web / Self-hosted:
> 
> Invidious (GitHub)
> MediaGoblin (Git)

PeerTube can be self-hosted as well.

> Web / P2P:
> 
> DTube (GitHub)
> Peertube (GitHub)
> KopyKate (GitHub) (appears dead)

I think it's important to note that you can disable the [p2p](https://github.com/Chocobozzz/PeerTube/issues/2030#issuecomment-530685224) player in PeerTube, because many people are concerned with most p2p technologies because they may leak a user's IP to others.

Currently there are only 2 ways to disable it:
- if the server admin has disabled it for the entire instance
- disable it your account settings

The feature that would allow non-registered users to disable the p2p player hasn't yet been developed https://github.com/Chocobozzz/PeerTube/issues/2271

**Comment by lrq3000** [comment] 2020-02-14 19:17
>I think it's important to note that you can disable the p2p player in PeerTube

I agree, that's a great point!

**Closed** 2020-07-27 15:30 UTC
Labels: approved, streaming, ✨ enhancement
