### ISSUE TITLE
🆕 Software Suggestion | Mattermost

### ISSUE THREAD

**Issue by Oymate** [privacytools/privacytools.io#2203] opened 2021-01-27 12:42 UTC
## Basic Information

**Name:** Mattermost
**Category:** Communication --> Team Chat
**URL:** https://mattermost.com/

## Description
Self-hosted team chat app. Has pinned post, announcements, channels and the normal stuff. Clean user interface and has webchat options.

## Why I am making the suggestion
Matter most is used by system76, wikipedia and other companies and foundations, so I thought it belongs here :-)

## My connection with the software
User

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment] 2021-01-27 14:22
Duplicate of #1066

**Closed by freddy-m** 2021-01-27 14:22 UTC
Labels: 🆕 software suggestion
