### ISSUE TITLE
🆕 Software Suggestion | Vivaldi Browser

### ISSUE THREAD

**Issue by KosmoEskudo** [privacytools/privacytools.io#2206] opened 2021-02-11 20:25 UTC
## Basic Information

**Name:** Vivaldi Browser
**Category:** Browsers
**URL:** https://vivaldi.com/

## Description

Chromium-based web browser with many unique features.

## Why I am making the suggestion

I have made an article on PrivacyTools Writefreely about Vivaldi. Inside the article are the sources.

Link to the article: https://write.privacytools.io/kolivro/vivaldi-and-privacy

## My connection with the software

I like the browser. Sometimes, user. I am not connected in any way with the creators of Vivaldi.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by LongJohn-Silver** [comment] 2021-02-11 21:21
I don' t think it should be listed, it probably phones to Google and Vivaldi servers, and it's not exactly a "libre" project since every browser except FF uses Chromium's code (and their CSS is proprietary). Yeah, it may have a lot of features but this is Tools for Power Users, it is Privacy Tools.

Besides all that, I don't think it is a good idea to not recommend the last existing non Chromium based broswer; FF stops existing and Google will decide what ammount of privacy you can achieve.

**Comment by freddy-m** [comment] 2021-02-13 11:09
Duplicate of #717

**Closed by freddy-m** 2021-02-13 11:09 UTC
Labels: 🆕 software suggestion

**Comment by KosmoEskudo** [comment] 2021-02-13 22:38
Please reopen https://github.com/privacytools/privacytools.io/issues/2206 (more recent) or https://github.com/privacytools/privacytools.io/pull/717 , since no one has said a *why* not to include it. I have researched Vivaldi, and have written up my findings in [this article](https://write.privacytools.io/kolivro/vivaldi-and-privacy) and I don't see a *why* not to include it.

The only thing that has been said is that it is closed source, and this issue is explained by Vivaldi [here](https://vivaldi.com/blog/vivaldi-browser-open-source/).

Translated with www.DeepL.com/Translator
