### ISSUE TITLE
❌ Software Removal | Signal

### ISSUE THREAD

**Issue by Baker-ux-dot** [privacytools/privacytools.io#2308] opened 2021-05-29 07:02 UTC
## Description
I suggest removing Signal.

## Why I am making the suggestion
At least on Android, it asks for a Google Captcha when I sign up.
This is undesirable from a privacy perspective.

## My connection with the software
user

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by rusty-snake** [comment] 2021-05-29 07:06
Duplicate of #779

**Comment by samuel-lucas6** [comment] 2021-06-03 09:47
I'm by no means a Signal fan but removing it is a bad idea because it's one of the better and most useable privacy messengers currently available. Lots of people seem to praise Element, but I've had problems like messages never being decrypted to the point that it was pointless using the platform. The element-web GitHub [repo](https://github.com/vector-im/element-web/issues) has nearly 5,000 open issues, so I'm clearly not the only person experiencing problems. Then the peer-to-peer messengers on the PrivacyTools website have limited use cases, with Briar only being available on Android. The current state of messengers is messy, much like the situation with browsers.

**Comment by freddy-m** [comment] 2021-06-03 21:08
Duplicate of #779

**Closed by freddy-m** 2021-06-03 21:08 UTC
Labels: ❌ software removal
