### ISSUE TITLE
🆕 Software Suggestion | /e/ OS for Android

### ISSUE THREAD

**Issue by atjn** [privacytools/privacytools.io#2188] opened 2021-01-12 14:26 UTC
## Basic Information

**Name:** /e/ OS
**Category:** [Android-based Operating Systems](https://privacytools.io/operating-systems/#aosp_os)
**URL:** https://e.foundation/

## Description
The /e/ foundation is trying to make privacy-respecting phones just as accessible and convenient as normal Android or iOS phones. /e/ does this by building their own versions of Android for hundreds of existing phones. Their OS has all Google services removed, does not track the user, is free, open-source, relatively accessible and has no vendor lock-in*. They are working on [an installer that automates the entire installation process](https://doc.e.foundation/easy-installer), and they also allow you to [buy an /e/ phone with /e/ OS preinstalled](https://esolutions.shop/).

/e/ also offers an optional [cloud service](https://e.foundation/products/#ecosystem) to offer the same convenience as the Google cloud does. If you want everything in your life to be perfectly decentralised and open-source, you can choose not to use this, but for normal users, this greatly reduces the barrier of entry while still mostly retaining the values that privacytools care about. I think it's a perfect solution.

I have flashed the /e/ OS to a few old phones, and my experience has been pretty good. It definitely isn't perfect, but I would say it is comparable to my experience using CalyxOS and LineageOS.

*I am not qualified to vet any of these claims. I am simply echoing what /e/'s own website says.

## Why I am making the suggestion
When privacy is equally good in many competing products, privacytools wants to show the overall best, most accessible, easiest-to-use ones ([source](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md#quality-over-quantity)). I would argue that the /e/ OS either meets or beats all the other OS'es in those benchmarks. It is supported on many more devices than CalyxOS and GrapheneOS, and it is much easier to install and use than the LineageOS builds are. I'm not saying the others should be removed in favor of /e/ OS, I'm just saying that this isn't simply adding "one more" option, it's adding the best option available.

/e/ OS is the first Google Android alternative I have seen that I would consider recommending to a less tech-savvy friend or family member.

## My connection with the software

I use it for some of my phones and I am very happy with it. I have no direct connection to /e/ or anyone working there.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

## What to do from here
I have no idea what the process is for adding something to privacytools. I would love to create a PR that does most of the work for you, but I am guessing there needs to be a discussion to vet and approve it first? As noted earlier, I don't have any intricate knowledge of /e/ as a company or platform. I am blindly trusting everything they say.

**Comment by freddy-m** [comment] 2021-01-17 13:49
Duplicate of #1393

**Closed by freddy-m** 2021-01-17 13:49 UTC
Labels: 🆕 software suggestion

**Comment by atjn** [comment] 2021-01-17 14:46
Alright thanks. I searched GitHub for similar issues before posting this, but nothing came up. Weird.
