### ISSUE TITLE
🆕 Software Suggestion | 

### ISSUE THREAD

**Issue by cbnavigator** [privacytools/privacytools.io#2370] opened 2021-07-11 13:37 UTC
## Basic Information

**Name:** openSUSE
**Category:** Operating systems
**URL:** https://www.opensuse.org/

## Description
[From openSUSE's wiki](https://en.opensuse.org/Portal:Distribution): The openSUSE distribution is a stable, easy to use and complete multi-purpose distribution. It is aimed towards users and developers working on the desktop or server. It is great for beginners, experienced users and ultra geeks alike, in short, it is perfect for everybody! The latest release, openSUSE Leap 15.3, features new and massively improved versions of all useful server and desktop applications. It comes with more than 1,000 open source applications. openSUSE Tumbleweed is the rolling release, providing the latest upstream software releases, yet only those packages that pass testing. openSUSE is also the base for SUSE's award-winning SUSE Linux Enterprise products.

## Why I am making the suggestion

At privacytools.io website, you'll notice that mainstream general-purpose distributions like Ubuntu, Debian, Fedora and Arch are mentioned but not openSUSE. openSUSE is IMO just as technically competent while being easy to install and easy to use as an Introductory Operating System, having a decades-old reputation and commitment to free and open source software. 

[GNU's endorsement of openSUSE](https://www.gnu.org/distros/common-distros.html) is only prevented by the inclusion a nonfree repository, which is added to the system by default but no packages from it are pre-installed (and the repository can be easily disabled). Any telemetry measures that I'm aware of are opt-in and expressely implemented by the user.

openSUSE's documentation provides a complete guide for [system security and hardening](https://doc.opensuse.org/documentation/leap/security/html/book-security/index.html).

## My connection with the software

I am merely an enthusiastic user of this Linux distribution and an admirer of its technical merits and most importantly of its committment to free and open-source software. However, I expect many others with connection to this distribution to also uphold this software suggestion.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by ph00lt0** [comment] 2021-07-11 13:41
duplicate of https://github.com/privacytools/privacytools.io/issues/2249

**Comment by ph00lt0** [comment] 2021-07-11 13:43
Please add the title of the software next time, and check for existing issues @cbnavigator

**Comment by cbnavigator** [comment] 2021-07-11 13:46
Very sorry, I did not notice the already opened issue. Thanks.

**Closed** 2021-07-11 13:45 UTC
Labels: 🆕 software suggestion
