### ISSUE TITLE
❌ Software Removal | Signal

### ISSUE THREAD

**Issue by cookiepanda1** [privacytools/privacytools.io#2357] opened 2021-06-25 00:48 UTC
## Description
Since Signal's server is effectively a closed source, I suggest that it be removed.

## Why I am making the suggestion
The source code for the Signal server is publicly available.
However, it is old.
In other words, it is effectively closed source.
Since Keybase has been removed and it has been decided that Threema will not be listed, Signal should also be removed.

## My connection with the software
Signal user

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by tomkel** [comment] 2021-06-25 04:18
They started pushing server code recently. About the time of the mobilecoin release.

https://github.com/signalapp/Signal-Server

**Comment by cookiepanda1** [comment] 2021-06-25 07:32
> They started pushing server code recently. About the time of the mobilecoin release.
> 
> https://github.com/signalapp/Signal-Server

But it is true that at one point earlier, they (virtually) did not release the source.
It is possible that they will stop releasing them again in the future.

**Comment by freddy-m** [comment] 2021-06-25 10:03
Duplicate of #779

**Closed by freddy-m** 2021-06-25 10:03 UTC
Labels: ❌ software removal
