### ISSUE TITLE
🆕 Software Suggestion | 

### ISSUE THREAD

**Issue by xKOSIUSx** [privacytools/privacytools.io#2226] opened 2021-03-04 12:47 UTC
## Basic Information

**Name:** Pirate Chain (ARRR)
**Category:** Privacy Coins - Cryptocurrency
**URL:** https://pirate.black/

## Description
Pirate Chain (ARRR) is a 100% private send cryptocurrency. It uses a privacy protocol that cannot be compromised by other users activity on the network. Most privacy coins are riddled with holes created by optional privacy. Pirate Chain uses zk-SNARKs to shield 100% of the peer to peer transactions on the blockchain making for highly anonymous and private transactions.

## Why I am making the suggestion
I'm suggesting this, because financial freedom and privacy should be on top of everybody's list.

## My connection with the software
I'm a team member of the Pirate project and we would love to collaborate with you guys in some way.

- [ ] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by freddy-m** [comment] 2021-03-04 21:57
Duplicate of #1694

**Closed by freddy-m** 2021-03-04 21:57 UTC
Labels: 🆕 software suggestion
