### ISSUE TITLE
✨ Feature Suggestion | Last Updated in footers

### ISSUE THREAD

**Issue by tEctutoRIt** [privacytools/privacytools.io#2198] opened 2021-01-19 18:33 UTC
## Description
Could you add "last updated : (date & time)" at the end of each page.
So people can know how up to date that page is. And it will be very helpful.

**Comment by LongJohn-Silver** [comment] 2021-01-19 21:18
Duplicate of #2104 which was closed in favour of #2079.

**Closed** 2021-01-20 08:14 UTC
Labels: ✨ enhancement
